### PR TITLE
Use vips to upsample webp 

### LINKED ISSUE #3262: Resizing then extracting Webp images past 16,383 now fails from sharp 0.30.x
### Is this a possible bug in a feature of sharp, unrelated to installation?

- [ x ] Running `npm install sharp` completes without error.
- [ x ] Running `node -e "require('sharp')"` completes without error.

### Are you using the latest version of sharp?

- [ x ] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

### What are the steps to reproduce?

Example  https://github.com/blacha/sharp-resize

### What is the expected behaviour?

In sharp 0.29.x I can resize a webp image to basically any size and then extract a region from the enlarged image without any issue. In sharp 0.30.x this now fails with `Error: webp: bad image dimensions`

```typescript
await sharp(buffer).resize(32768, 32768)
  .extract({ top: 16384, left: 16384, width: 1024, height: 1024 })
  .webp().toBuffer();
```

I see some work was done in libvips recently to improve image resizing especially with SVGs, is there a easy way to go back to the old resizing method?

### Please provide a minimal, standalone code sample, without other dependencies, that demonstrates this problem

Example  https://github.com/blacha/sharp-resize

### Please provide sample image(s) that help explain this problem

Sample image in repo.

### PR DESCRIPTION
**Pull request by blacha**
When scaling WebP images up past 16383 x 16383 use vips scaling logic to prevent `Error: webp: bad image dimensions`

Fixes #3262

### CODE REVIEW

File: src/pipeline.cc [hunk 1]
```diff
@@ -217,7 +217,7 @@ class PipelineWorker : public Napi::AsyncWorker {
           ->set("access", baton->input->access)
           ->set("scale", scale)
           ->set("fail_on", baton->input->failOn);
-        if (inputImageType == sharp::ImageType::WEBP) {
+        if (scale < 1.0 && inputImageType == sharp::ImageType::WEBP) {
```
Comment (kleisauke) [inline src/pipeline.cc:220]: This causes a small memory leak for the dynamic-allocated `*option` when `scale > 1.0`, since it's never `delete`'d. How about doing this?
```diff
--- a/src/pipeline.cc
+++ b/src/pipeline.cc
@@ -188,8 +188,10 @@ class PipelineWorker : public Napi::AsyncWorker {
           if (jpegShrinkOnLoad > 1 && static_cast<int>(shrink) == jpegShrinkOnLoad) {
             jpegShrinkOnLoad /= 2;
           }
-        } else if (inputImageType == sharp::ImageType::WEBP ||
-                   inputImageType == sharp::ImageType::SVG ||
+        } else if (inputImageType == sharp::ImageType::WEBP && shrink > 1.0) {
+          // Avoid upscaling via libwebp
+          scale = 1.0 / shrink;
+        } else if (inputImageType == sharp::ImageType::SVG ||
                    inputImageType == sharp::ImageType::PDF) {
           scale = 1.0 / shrink;
         }
```

**Comment by lovell** [comment]
Brilliant, thank you for fixing this (and thanks Kleis for reviewing).

**Comment by blacha** [comment]
Awesome than you both! Libvips/sharp are amazing tools! 

When do you think a release for this will happen?

**Comment by lovell** [comment]
@blacha This will be part of v0.30.7, probably some time later this week ahead of the work to test the forthcoming libvips v8.13.0.
